# Description: Config for train.py script

# Name of experiment
experiment_name: 3 - Ridge Regression
# Description
description: Train linear regression on color and HOG features.

is_regression: True
predicted_file: predicted.npz

model: Ridge(alpha=1.0)
