# Description: Config for train.py script

# Name of experiment
experiment_name: 4 - DecisionTreeRegressor
# Description
description: Train DecisionTreeRegressor on Float128.

is_regression: True
predicted_file: predicted.npz

model: DecisionTreeRegressor
