# Description: Config for train.py script

# Name of experiment
experiment_name: 4 - SVR
# Description
description: Train SVR on color and HOG features.

is_regression: True
predicted_file: predicted.npz

model: SVR
