# Description: Config for train.py script

# Name of experiment
experiment_name: 1 - Colors
# Description
description: Test manual features train pipeline

is_regression: True
predicted_file: predicted.npz

model: Ridge(alpha=1.0)
