# Description: Config for train.py script

# Name of experiment
experiment_name: 7 - Train top then unfreeze Xception 10%
# Description
description: Train top layers and then unfreeze 10% of layers in Xception.

# Pretrained model name
model_name: Xception
is_regression: False

data_dir: 144k_flow_exif
number_of_classes: 10

# Network training params
batch_size: 32
num_epoches: 200
num_epoches_top_train: 50
# num_epoches: 3
loss: categorical_crossentropy
optimizer: rmsprop
metrics: ['accuracy']

# Names for log files
model_file: model.h5
architecture_file: model.json
logs_file: model.log
predicted_file: predicted.npz

# For reproducable results
numpy_seed: 113
tensorflow_seed: 114 