# Author: Maria Sandrikova
# Description: Config for train.py script

# Name of experiment
experiment_name: Autumn NIR control
# Description
description: Add Dense layer to fixed Xception model

# Pretrained model name
model_name: Xception
is_regression: False

data_dir: 144k_flow
number_of_classes: 10

# Network training params
batch_size: 32
#num_epoches: 300
num_epoches: 20
number_of_dense: 1
loss: categorical_crossentropy
optimizer: rmsprop
metrics: ['accuracy']

# Names for log files
model_file: model.json
weights_file: model.h5
logs_file: model.log
predicted_file: predicted.npz

# For reproducable results
numpy_seed: 113
tensorflow_seed: 114 