# Description: Config for train.py script

# Name of experiment
experiment_name: 2 - LinearRegression
# Description
description: Train LinearRegression on color and HOG features plus Float128.

is_regression: True
predicted_file: predicted.npz

model: LinearRegression
