# Description: Config for train.py script

# Name of experiment
experiment_name: More custom layers
# Description
description: Add Dropout and Dense layers 

# Pretrained model name
model_name: Xception

data_dir: 144k_flow_exif
number_of_classes: 10

# Network training params
batch_size: 32
num_epoches: 200
# num_epoches: 3
loss: categorical_crossentropy
optimizer: rmsprop
metrics: ['accuracy']

# Names for log files
model_file: model.json
weights_file: model.h5
logs_file: model.log
predicted_file: predicted.npz

# For reproducable results
numpy_seed: 113
tensorflow_seed: 114 