# Description: Config for train.py script

# Name of experiment
experiment_name: 1 - Test
# Description
description: Test cloth comparation algorithm on 13k photos

is_regression: True
predicted_file: predicted.npz

model: Cloth comparation
