# Description: Config for train.py script

# Name of experiment
experiment_name: 7 - Unfreeze Xception with augmentation
# Description
description: Unfreeze 20% of Xception layers with data augmentation

# Pretrained model name
model_name: Xception
is_regression: True

data_dir: 144k_flow_exif
number_of_classes: 10
#data_dir: 17flowers_flow
#number_of_classes: 17

# Network training params
batch_size: 32
num_epoches: 200
#num_epoches: 3 

loss: mean_absolute_error
optimizer: rmsprop
metrics: ['mean_squared_error', 'mean_absolute_error']

# Names for log files
model_file: model.h5
architecture_file: model.json
logs_file: model.log
predicted_file: predicted.npz

# For reproducable results
numpy_seed: 113
tensorflow_seed: 114 